# obstacle_range: 2.5
# raytrace_range: 3.0
# path_planned: [3.0, 0.0,  
#                3.0, 3.0,
#                3.0, 6.0,
#                0.0, 6.0,
#                0.0, 0.0,
#                7.0, 1.0]
#robot_radius: ir_of_robot
# inflation_radius: 0.55

# Parking-lot simple loop.
path_planned: [63.0, 0.00,  
               63.0, 43.0,
               56.0, 43.0,
               56.0, 6.00,
               0.00, 6.00,
               0.00, 0.00]

position_topic: /odom

trans_velocity_max: 0.6
trans_velocity_min: 0.05
angular_velocity_max: 1.0
angular_velocity_min: 0.03

sample_time: 0.05
KP_rotate: 1.0
KP_trans: 1.0
p_value: 1.0